sudo: required
language: java
jdk: openjdk8

services:
- docker

script:
- mvn clean package -Dmaven.test.skip=true

after_success:
- echo $DOCKER_USER
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker build -t cecily/register .
- docker images
- docker tag cecily/register cccancc/travistest:a
- docker push cccancc/travistest:a
#- docker run -p 8200:10001 -d cccancc/travistest:8-jdk-alpine
# - export IMAGE_NAME=cecily/register
# - docker build -t cecily/register .
# - docker run -d -p 8100:10001 -d cecily/register

notification:
  email: false
  slack: ibm-cio:jFJaiViSqchWmOKeLurBriPN
  secure: "jFJaiViSqchWmOKeLurBriPN"
